"use client";

import {
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  GitCompareArrows,
  Route,
  ShieldCheck,
  XCircle,
} from "lucide-react";
import { useState } from "react";

type ConformanceDeviation = {
  type: string;
  after_activity: string;
  expected_activity: string;
  observed_activity: string;
  detail: string;
};

type RoutingDecision = {
  from_activity: string;
  expected_next: string | null;
  observed_next: string | null;
  matched_rule_label: string;
  matched_rule: boolean;
};

type ConformanceRun = {
  run_id: number;
  status: string;
  path: string[];
  conformant: boolean;
  deviation_count: number;
  deviations: ConformanceDeviation[];
  routing_decisions: RoutingDecision[];
};

export type ProcessMiningConformance = {
  mode: string;
  checked_runs: number;
  conformant_runs: number;
  nonconformant_runs: number;
  conformance_score: number;
  designed_path: string[];
  designed_edges: Array<{
    source: string;
    target: string;
    kind: string;
    label: string;
  }>;
  deviation_counts: Record<string, number>;
  runs: ConformanceRun[];
};

type Props = {
  conformance: ProcessMiningConformance;
  defaultExpanded?: boolean;
};

function formatDeviationType(value: string): string {
  return value
    .split("_")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

function evidenceLabel(checkedRuns: number): string {
  if (checkedRuns < 5) return "Limited evidence";
  if (checkedRuns < 20) return "Growing evidence";
  return "Stronger evidence";
}

export function ConformanceCheckingPanel({ conformance, defaultExpanded = true }: Props) {
  const [expanded, setExpanded] = useState(defaultExpanded);
  const [expandedRuns, setExpandedRuns] = useState<Record<number, boolean>>({});
  const conditionalEdges = conformance.designed_edges.filter(
    (edge) => edge.kind === "conditional",
  );

  const toggleRun = (runId: number) => {
    setExpandedRuns((current) => ({
      ...current,
      [runId]: !current[runId],
    }));
  };

  const scoreMeaning = conformance.checked_runs > 0
    ? `${conformance.conformance_score.toFixed(1)}% means ${conformance.conformant_runs} of ${conformance.checked_runs} checked runs followed the workflow structure and routing rules that were expected for those executions.`
    : "No executions have been checked yet.";

  return (
    <div className="rounded-2xl border border-[#DCE4EE] bg-white p-6 shadow-[0_1px_2px_rgba(25,50,76,0.05)]">
      <div className="flex flex-wrap items-start justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <GitCompareArrows className="size-4 text-[#3569B8]" aria-hidden />
            <h3 className="text-[16px] font-semibold text-[#202126]">
              Conformance Checking
            </h3>
          </div>
          <p className="mt-1 max-w-[760px] text-[12px] leading-5 text-[#7D858D]">
            Compares each observed execution with the workflow and routing rules generated by the Builder. A conditional branch is conformant when the runtime follows the route implied by the source Agent output.
          </p>
        </div>
        <div className="flex items-center gap-2">
          <span className="rounded-full border border-[#DCE4EE] bg-[#F8FAFC] px-3 py-1 text-[10px] font-semibold uppercase tracking-[0.08em] text-[#6C7883]">
            {conformance.mode}
          </span>
          <button
            type="button"
            onClick={() => setExpanded((value) => !value)}
            aria-expanded={expanded}
            className="inline-flex items-center gap-1.5 rounded-lg border border-[#DCE4EE] bg-white px-3 py-1.5 text-[11px] font-semibold text-[#59636C] transition hover:bg-[#F6F8FA]"
          >
            {expanded ? <ChevronDown className="size-3.5" aria-hidden /> : <ChevronRight className="size-3.5" aria-hidden />}
            {expanded ? "Collapse" : "Expand"}
          </button>
        </div>
      </div>

      {!expanded ? (
        <div className="mt-4 flex flex-wrap items-center gap-3 text-[11px] text-[#69737C]">
          <span className="rounded-lg bg-[#F6F8FA] px-3 py-2 font-semibold text-[#30343A]">
            {conformance.conformance_score.toFixed(1)}% conformance
          </span>
          <span>{conformance.conformant_runs}/{conformance.checked_runs} runs conformant</span>
          <span>{conformance.nonconformant_runs} deviating</span>
        </div>
      ) : (
        <>
          <div className="mt-5 grid gap-3 sm:grid-cols-3">
            <div className="rounded-xl border border-[#E5E9ED] bg-[#FAFBFC] p-4">
              <p className="text-[11px] font-semibold uppercase tracking-[0.08em] text-[#8B949D]">Conformance Score</p>
              <div className="mt-2 flex items-center gap-2">
                <ShieldCheck className="size-5 text-[#3569B8]" aria-hidden />
                <p className="text-[22px] font-semibold text-[#202126]">{conformance.conformance_score.toFixed(1)}%</p>
              </div>
            </div>
            <div className="rounded-xl border border-[#E5E9ED] bg-[#FAFBFC] p-4">
              <p className="text-[11px] font-semibold uppercase tracking-[0.08em] text-[#8B949D]">Conformant Runs</p>
              <p className="mt-2 text-[22px] font-semibold text-[#202126]">{conformance.conformant_runs} / {conformance.checked_runs}</p>
            </div>
            <div className="rounded-xl border border-[#E5E9ED] bg-[#FAFBFC] p-4">
              <p className="text-[11px] font-semibold uppercase tracking-[0.08em] text-[#8B949D]">Deviating Runs</p>
              <p className="mt-2 text-[22px] font-semibold text-[#202126]">{conformance.nonconformant_runs}</p>
            </div>
          </div>

          <div className="mt-4 rounded-xl border border-[#DCE4EE] bg-[#F7FAFE] px-4 py-3">
            <p className="text-[12px] font-semibold text-[#315F9D]">What does {conformance.conformance_score.toFixed(1)}% mean?</p>
            <p className="mt-1 text-[11px] leading-5 text-[#66727D]">
              {scoreMeaning} It does not mean the workflow is 100% correct, fast, or optimal. It only measures agreement between designed and observed execution behavior.
            </p>
            <p className="mt-1 text-[10px] font-semibold uppercase tracking-[0.08em] text-[#87919A]">
              {evidenceLabel(conformance.checked_runs)} · {conformance.checked_runs} checked run{conformance.checked_runs === 1 ? "" : "s"}
            </p>
          </div>

          <div className="mt-5 grid gap-4 xl:grid-cols-2">
            <div className="rounded-xl border border-[#E5E9ED] bg-[#FAFBFC] p-4">
              <div className="flex items-center gap-2">
                <Route className="size-4 text-[#3569B8]" aria-hidden />
                <p className="text-[12px] font-semibold text-[#30343A]">Designed Workflow</p>
              </div>
              <div className="mt-3 flex flex-wrap items-center gap-2 text-[12px] text-[#4D5660]">
                {conformance.designed_path.map((name, index) => (
                  <div key={`${name}-${index}`} className="flex items-center gap-2">
                    <span className="rounded-lg border border-[#DCE4EE] bg-white px-2.5 py-1.5 font-medium">{name}</span>
                    {index < conformance.designed_path.length - 1 ? <span className="text-[#A2AAB2]">→</span> : null}
                  </div>
                ))}
              </div>
              {conditionalEdges.length > 0 ? (
                <div className="mt-4 border-t border-[#E5E9ED] pt-3">
                  <p className="text-[10px] font-bold uppercase tracking-[0.1em] text-[#919AA3]">Conditional routes</p>
                  <div className="mt-2 space-y-2">
                    {conditionalEdges.map((edge, index) => (
                      <div key={`${edge.source}-${edge.target}-${index}`} className="rounded-lg border border-[#DCE4EE] bg-white px-3 py-2 text-[11px] text-[#59636C]">
                        <span className="font-semibold text-[#30343A]">{edge.source}</span>
                        <span className="mx-2">→</span>
                        <span className="font-semibold text-[#30343A]">{edge.target}</span>
                        <span className="ml-2 text-[#7D858D]">when {edge.label}</span>
                      </div>
                    ))}
                  </div>
                </div>
              ) : null}
            </div>

            <div className="rounded-xl border border-[#E5E9ED] bg-[#FAFBFC] p-4">
              <p className="text-[12px] font-semibold text-[#30343A]">Detected Deviations</p>
              {Object.keys(conformance.deviation_counts).length === 0 ? (
                <div className="mt-3 flex items-start gap-2 rounded-lg border border-[#CFE6D8] bg-[#F2FBF5] px-3 py-3">
                  <CheckCircle2 className="mt-0.5 size-4 shrink-0 text-[#397A50]" aria-hidden />
                  <p className="text-[11px] leading-5 text-[#4E6B58]">No routing deviation was detected in the analyzed executions.</p>
                </div>
              ) : (
                <div className="mt-3 space-y-2">
                  {Object.entries(conformance.deviation_counts).map(([type, count]) => (
                    <div key={type} className="flex items-center justify-between rounded-lg border border-[#F0D4D0] bg-[#FFF7F5] px-3 py-2 text-[11px]">
                      <span className="font-medium text-[#7A4740]">{formatDeviationType(type)}</span>
                      <span className="font-semibold text-[#B4493F]">{count}</span>
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>

          <div className="mt-5">
            <p className="text-[12px] font-semibold text-[#30343A]">Recent Run Checks</p>
            <div className="mt-3 space-y-3">
              {conformance.runs.slice(0, 8).map((run) => {
                const matchedDecisions = run.routing_decisions.filter((decision) => decision.matched_rule);
                const runExpanded = expandedRuns[run.run_id] ?? false;
                return (
                  <div key={run.run_id} className="rounded-xl border border-[#E5E9ED] bg-[#FAFBFC] p-4">
                    <div className="flex flex-wrap items-center justify-between gap-3">
                      <div className="flex items-center gap-2">
                        {run.conformant ? (
                          <CheckCircle2 className="size-4 text-[#397A50]" aria-hidden />
                        ) : (
                          <XCircle className="size-4 text-[#C9564C]" aria-hidden />
                        )}
                        <span className="text-[12px] font-semibold text-[#30343A]">Run #{run.run_id}</span>
                        <span className="text-[10px] uppercase tracking-[0.08em] text-[#8B949D]">{run.status}</span>
                      </div>
                      <div className="flex items-center gap-2">
                        <span className={`rounded-full px-2.5 py-1 text-[10px] font-semibold ${run.conformant ? "bg-[#EAF6EE] text-[#397A50]" : "bg-[#FCECEA] text-[#B4493F]"}`}>
                          {run.conformant ? "Conformant" : `${run.deviation_count} deviation${run.deviation_count === 1 ? "" : "s"}`}
                        </span>
                        <button
                          type="button"
                          onClick={() => toggleRun(run.run_id)}
                          aria-expanded={runExpanded}
                          className="inline-flex items-center gap-1 rounded-md border border-[#DCE4EE] bg-white px-2 py-1 text-[10px] font-semibold text-[#59636C] transition hover:bg-[#F6F8FA]"
                        >
                          {runExpanded ? <ChevronDown className="size-3" aria-hidden /> : <ChevronRight className="size-3" aria-hidden />}
                          {runExpanded ? "Hide" : "Details"}
                        </button>
                      </div>
                    </div>

                    <div className="mt-3 flex flex-wrap items-center gap-1.5 text-[11px] text-[#59636C]">
                      {run.path.map((name, index) => (
                        <div key={`${run.run_id}-${name}-${index}`} className="flex items-center gap-1.5">
                          <span className="rounded-md border border-[#DCE4EE] bg-white px-2 py-1">{name}</span>
                          {index < run.path.length - 1 ? <span className="text-[#A2AAB2]">→</span> : null}
                        </div>
                      ))}
                    </div>

                    {runExpanded ? (
                      <>
                        {matchedDecisions.length > 0 ? (
                          <div className="mt-3 space-y-1.5">
                            {matchedDecisions.map((decision, index) => (
                              <p key={`${run.run_id}-decision-${index}`} className="text-[11px] leading-5 text-[#59636C]">
                                <span className="font-semibold text-[#3569B8]">Conditional route:</span>{" "}
                                {decision.from_activity} → {decision.expected_next ?? "END"}
                                {decision.matched_rule_label ? ` (${decision.matched_rule_label})` : ""}. Observed: {decision.observed_next ?? "END"}.
                              </p>
                            ))}
                          </div>
                        ) : (
                          <p className="mt-3 text-[11px] leading-5 text-[#7D858D]">No conditional routing rule was triggered in this run.</p>
                        )}

                        {run.deviations.length > 0 ? (
                          <div className="mt-3 space-y-2">
                            {run.deviations.map((deviation, index) => (
                              <div key={`${run.run_id}-dev-${index}`} className="rounded-lg border border-[#F0D4D0] bg-[#FFF7F5] px-3 py-2 text-[11px] leading-5 text-[#7A4740]">
                                <span className="font-semibold">{formatDeviationType(deviation.type)}:</span> {deviation.detail}
                              </div>
                            ))}
                          </div>
                        ) : null}
                      </>
                    ) : null}
                  </div>
                );
              })}
            </div>
          </div>
        </>
      )}
    </div>
  );
}
