"use client";

import {
  ArrowLeft,
  Bot,
  Clock,
  Play,
  Workflow as WorkflowIcon,
} from "lucide-react";

import type {
  WorkflowAgent,
} from "./RunGraphPanel";

export type WorkflowOverviewData = {
  id: number;
  name: string;
  status: string;
  created_at: string;
  updated_at: string;
  agents: WorkflowAgent[];
};

type WorkflowOverviewHeaderProps = {
  workflow: WorkflowOverviewData;
  onBack: () => void;
  onRun: () => void;
};

function normalizeDateValue(
  value: string,
): string {
  if (!value) {
    return value;
  }

  return value.includes("T")
    ? value
    : value.replace(" ", "T");
}

function formatDate(
  value: string,
): string {
  if (!value) {
    return "Unknown date";
  }

  const date = new Date(
    normalizeDateValue(value),
  );

  if (Number.isNaN(date.getTime())) {
    return value;
  }

  return date.toLocaleString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
}

function getStatusClasses(
  status: string,
): string {
  switch (status) {
    case "published":
    case "active":
      return "bg-[#EEF6F0] text-[#438252]";

    case "draft":
      return "bg-[#F1F4F7] text-[#68727B]";

    case "archived":
      return "bg-[#FFF0E8] text-[#D95117]";

    default:
      return "bg-[#EDF4FC] text-[#3569B8]";
  }
}

export function WorkflowOverviewHeader({
  workflow,
  onBack,
  onRun,
}: WorkflowOverviewHeaderProps) {
  const canRun =
    workflow.agents.length > 0;

  return (
    <>
      <div className="flex flex-wrap items-center justify-between gap-4">
        <button
          type="button"
          onClick={onBack}
          className="flex items-center gap-2 text-[14px] font-semibold text-[#3569B8] transition hover:text-[#2F5FA8]"
        >
          <ArrowLeft
            className="size-4"
            aria-hidden
          />

          Back to My Agent Teams
        </button>

        <button
          type="button"
          onClick={onRun}
          disabled={!canRun}
          className="inline-flex items-center gap-2 rounded-lg bg-[#3569B8] px-4 py-2.5 text-[14px] font-semibold text-white transition hover:bg-[#2F5FA8] disabled:cursor-not-allowed disabled:opacity-50"
        >
          <Play
            className="size-4"
            aria-hidden
          />

          Run Agent Team
        </button>
      </div>

      <header className="mt-6 rounded-2xl border border-[#DCE4EE] bg-white px-7 py-6 shadow-[0_1px_2px_rgba(25,50,76,0.05)]">
        <div className="flex items-start gap-4">
          <span className="flex size-12 shrink-0 items-center justify-center rounded-xl bg-[#E8F0FB] text-[#3569B8]">
            <WorkflowIcon
              className="size-6"
              aria-hidden
            />
          </span>

          <div className="min-w-0 flex-1">
            <div className="flex flex-wrap items-center gap-3">
              <h1 className="text-[27px] font-semibold tracking-[-0.02em] text-[#202126]">
                {workflow.name}
              </h1>

              <span
                className={[
                  "rounded-full px-3 py-1 text-[11px] font-semibold capitalize",
                  getStatusClasses(
                    workflow.status,
                  ),
                ].join(" ")}
              >
                {workflow.status}
              </span>
            </div>

            <div className="mt-3 flex flex-wrap items-center gap-x-5 gap-y-2 text-[13px] text-[#73757A]">
              <span className="flex items-center gap-1.5">
                <Bot
                  className="size-3.5"
                  aria-hidden
                />

                {workflow.agents.length}{" "}
                {workflow.agents.length === 1
                  ? "agent"
                  : "agents"}
              </span>

              <span className="flex items-center gap-1.5">
                <Clock
                  className="size-3.5"
                  aria-hidden
                />

                Published{" "}
                {formatDate(
                  workflow.created_at,
                )}
              </span>
            </div>

            <p className="mt-4 max-w-[760px] text-[14px] leading-6 text-[#73757A]">
              Agents execute in the configured order. Each agent
              receives the output generated by the previous step.
            </p>
          </div>
        </div>
      </header>
    </>
  );
}